##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    use_usd_kinematics: False
    usd_path: "robot/sagittarius/K1.usd"
    usd_robot_root: "/robot"
    isaac_usd_path: ""
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: "robot/sagittarius/K1.urdf"
    asset_root_path: "robot/sagittarius/"
    
    base_link: "sagittarius_base_link"
    ee_link: "link_grasping_frame"
    link_names: null
    lock_joints: null
    extra_links: null

    #TODO: Add collision link names and spheres
    collision_link_names: ["link1", "link2", "link3", "link4", "link5", "link6", "link_gripper_left", "link_gripper_right"]
    collision_spheres: "spheres/K1_collision_mesh.yml"
    collision_sphere_buffer: 0.0 # float or Dict[str, float]
    extra_collision_spheres: {} # Dict[str, List[str]]
    self_collision_ignore: {
      "link1": ["link2"],
      "link2": ["link3"],
      "link3": ["link4"],
      "link4": ["link5"],
      "link5": ["link6"],
      "link6": ["link_gripper_left", "link_gripper_right"],
      "link_gripper_left": ["link_gripper_right"],
    }
    self_collision_buffer: {
      "link1": 0.0,
      "link2": 0.0,
      "link3": 0.0,
      "link4": 0.0,
      "link5": 0.0,
      "link6": 0.0,
      "link_gripper_left": 0.0,
      "link_gripper_right": 0.0,
    }

    use_global_cumul: True
    mesh_link_names: null # List[str]
    external_asset_path: null # Use this to add path for externally located assets/robot folder.

    cspace:
      joint_names: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "joint_gripper_left", "joint_gripper_right"] # List[str]
      retract_config: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # List[float]
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # List[str]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # List[str]
      max_jerk: 500.0
      max_acceleration: 15.0
